rent_and_deal_car/accounts/urls.py
from django.urls import path, include, reverse_lazy
import accounts.views as views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("register", views.register, name="register"),
    path("login_user", views.login_user, name="login_user"),
    path("logout_user", views.logout_user, name="logout_user"),
    path("home", views.home, name="home"),
    path('reset/', include('django.contrib.auth.urls')),
    path("password_reset/", auth_views.PasswordResetView.as_view(

        success_url=reverse_lazy("password_reset_done"),
        template_name="remind_password/password_reset_form.html",
        email_template_name="remind_password/password_reset_email.html",
    ), name="password_reset"),

    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="remind_password/password_reset_done.html"
        ),
        name="password_reset_done",
    ),

    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="remind_password/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="remind_password/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

rent_and_deal_car/car_rent/urls.py
from django.conf.urls.static import static
from django.urls import path

from rent_and_deal_car import settings
from .views import ListOfBranches, ModelList,\
    ListOfRentalOffers, home, RentalOfferView, CarRentalDetails, ReturnCar,\
    AdminPanel, AccountDetails, CompleteDetails, AccountPayment

app_name = "car_rent"

urlpatterns = [
    path("", home, name="home"),
    path('admin/', AdminPanel.as_view(), name="switch-admin"),
    path('branches/', ListOfBranches.as_view(), name="list-of-branch"),
    path('listmodel/', ModelList.as_view(), name="list-model"),
    path('list_of_offers/', ListOfRentalOffers.as_view(), name="list-of-rental-offers"),
    path('offer/<int:RentalOffer_id>', RentalOfferView.as_view, name="rental-offer"),
    path('car_rental/<int:id>', CarRentalDetails.as_view(), name="car_rental"),
    path('car_rental_succesfull/', CarRentalDetails.as_view(), name="car_rental_succesfull"),
    path('car_rental_return/<int:id>', ReturnCar.as_view(), name="car_rental_return"),
    path('account_details/', AccountDetails.as_view(), name="account-details"),
    path('account-complete/', CompleteDetails.as_view(), name="account-complete"),
    path('account-payment/', AccountPayment.as_view(), name="account-payment"),
]

rent_and_deal_car/rent_and_deal_car/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include("car_rent.urls")),
    path('accounts/', include('accounts.urls')),
   ]

rent_and_deal_car/car_rent/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Vehicle, Branch, Brand, Model, RentalOffer, CarRental


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name',)


class CustomUserCompleteDetails(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('street', 'house_number', 'zip_code',
                  'city', 'credit_card_nr', 'expiration',
                  'CVV', 'mobile')


class PaymentForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('credit_card_nr', 'balance',  'password',)


class BranchCreate(forms.ModelForm):
    class Meta:
        model = Branch
        fields = ('address', 'city', 'open_from', 'open_till',
                  'mail', 'mobile', 'remarks')


class VehicleModelForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = ('model_id', 'body_type', 'prod_year',
                  'color', 'engine', 'type_of_fuel',
                  'transmission', 'vin')


class BrandModelForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = ('name',)


class CarModelModelForm(forms.ModelForm):
    class Meta:
        model = Model
        fields = ('brand_id', 'name',)


class RentalOfferCreate(forms.ModelForm):
    class Meta:
        model = RentalOffer
        fields = ('Vehicle_Id', 'Categories',
                  'Description', 'Deposit', 'Price_per_day')


class CarRentalForm(forms.ModelForm):
    class Meta:
        model = CarRental
        fields = ('customer_id', 'rental_offer_id', 'total_price')

rent_and_deal_car/car_rent/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View

from .forms import CustomUserCompleteDetails, PaymentForm
from .models import Branch, Vehicle, Model, RentalOffer, CarRental, CustomUser
import datetime

User = get_user_model()


def home(request):
    vehicles = Vehicle.objects.all()
    ctx = {'vehicles': vehicles}

    return render(request, "car_rent/home.html", context=ctx)


class AccountDetails(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = CustomUser.objects.get(id=request.user.id)

        account = [user.first_name, user.last_name, user.street, user.house_number,
                   user.zip_code, user.city, user.credit_card_nr, user.mobile]
        count = 0
        for i in account:
            if len(str(i)) is 0 or i is None:
                count += 1
        if count > 0:
            ctx = {'user': user, 'count': count}
        else:
            ctx = {'user': user}
        return render(self.request, "car_rent/account_details.html", context=ctx)


class AdminPanel(View):
    def get(self, request, *args, **kwargs):
        return render(request, "admin")


class ListOfBranches(View):
    def get(self, request, *args, **kwargs):
        list_of_branches = Branch.objects.all()
        ctx = {'list_of_branches': list_of_branches}
        return render(self.request, 'car_rent/list_of_branches.html', context=ctx)


class ListOfRentalOffers(View):
    def get(self, request, *args, **kwargs):
        list_of_offers = RentalOffer.objects.all()
        vehicles = Vehicle.objects.all()
        user = CustomUser.objects.get(id=request.user.id)
        car_rentals = CarRental.objects.filter(customer_id=user.id)
        car_rental_availability = CarRental.objects.filter(is_rented=True)
        branch = Branch.objects.all()
        list = []

        for a in car_rental_availability:
            list.append(a.rental_offer_id.id)

        if list:
            print("List")
        else:
            print("No list")
        ctx = {'list_of_offers': list_of_offers, 'branch': branch,
               'vehicles': vehicles, 'car_rental_availability': list}

        for customer_record in car_rentals:
            if customer_record.is_rented:
                ctx['rented'] = customer_record.rental_offer_id.id
                return render(request, "car_rent/list_of_offers.html", context=ctx)

        return render(self.request, 'car_rent/list_of_offers.html', context=ctx)


class RentalOfferView(View):
    def get(self, request, rental_offer_id, *args, **kwargs):
        try:
            rental_offer = RentalOffer.objects.get(id=rental_offer_id)
            vehicles = Vehicle.objects.all()
            ctx = {"rental_offer": rental_offer, 'vehicles': vehicles}
        except RentalOffer.DoesNotExist:
            ctx = {'rental_offer_id': id}
        return render(request, "car_rent/offer.html", context=ctx)


class ModelList(View):
    def get(self, request, *args, **kwargs):
        model = Model.objects.all()
        ctx = {'model': model}

        return render(self.request, "car_rent/model_list.html", context=ctx)


class CarRentalDetails(LoginRequiredMixin, View):
    def get(self, request, id, *args, **kwargs):
        try:
            offer = RentalOffer.objects.get(id=id)

        except RentalOffer.DoesNotExist:
            return HttpResponse("This offer does not exist")

        date = datetime.date.today()
        '''Take loged user'''
        user = CustomUser.objects.get(id=request.user.id)
        '''Take all record for user who rent any car'''
        car_rentals = CarRental.objects.filter(customer_id=user.id)

        for customer_record in car_rentals:
            '''
            If the user is still renting any car then return rented is True then not have option to rent
            '''
            if customer_record.is_rented:
                ctx = {"offer": offer, "date": date, 'rented': True}
                return render(request, "car_rent/car_rental.html", context=ctx)

        ctx = {"offer": offer, "date": date}
        return render(request, "car_rent/car_rental.html", context=ctx)

    def post(self, request, id, *args, **kwargs):
        try:
            offer = RentalOffer.objects.get(id=id)
            user = CustomUser.objects.get(id=request.user.id)

        except RentalOffer.DoesNotExist:
            return HttpResponse("This offer does not exist")

        date = datetime.date.today()
        ctx = {'offer': offer, "date": date, 'user': user}

        user_details = [user.street, user.house_number, user.zip_code, user.city,
                        user.credit_card_nr, user.expiration, user.CVV, user.mobile]

        car_rentals = CarRental.objects.filter(rental_offer_id=offer.id, is_rented=True)


        if None not in user_details:
            if user.balance - offer.Deposit >= 0:
                if car_rentals:
                    messages.info(self.request, "Someone already rented this car")
                    return render(self.request, "car_rent/car_rental.html", context=ctx)
                else:
                    user.balance -= offer.Deposit
                    car_rental = CarRental.objects.create(customer_id=user, rental_offer_id=offer, is_rented=True)
                    user.save()
                    car_rental.save()

                    return render(request, "car_rent/car_rental_succusfull.html", context=ctx)

            else:
                messages.info(self.request, "You haven't enough cash to pay deposit for car, on your account. ")
                return render(self.request, "car_rent/car_rental.html", context=ctx)
        else:
            messages.info(self.request, "Before renting, please enter your address and payment method")
            return render(self.request, "car_rent/car_rental.html", context=ctx)


def date_counter(date_of_rent):
    """Date Counter when car is returned"""
    today = datetime.date.today()
    time_rent = today - date_of_rent
    return time_rent.days + 1


class ReturnCar(LoginRequiredMixin, View):
    def get(self, request, id, *args, **kwargs):
        try:
            offer = RentalOffer.objects.get(id=id)

        except RentalOffer.DoesNotExist:
            return HttpResponse("This offer does not exist")

        user = CustomUser.objects.get(id=request.user.id)
        car_rental = CarRental.objects.get(customer_id=user, rental_offer_id=offer, is_rented=True)
        date = datetime.date.today()
        total_price = date_counter(car_rental.date_of_rent) * offer.Price_per_day

        ctx = {"offer": offer, "date": date, 'total_price': total_price}
        return render(request, "car_rent/car_rental_return.html", context=ctx)

    def post(self, request, id, *args, **kwargs):
        try:
            offer = RentalOffer.objects.get(id=id)

        except RentalOffer.DoesNotExist:
            return HttpResponse()


        user = CustomUser.objects.get(id=request.user.id)
        car_rental = CarRental.objects.get(customer_id=user, rental_offer_id=offer, is_rented=True)
        total_price = date_counter(car_rental.date_of_rent) * offer.Price_per_day
        car_rental.is_rented = False
        car_rental.total_price = total_price

        user.balance += offer.Deposit
        user.balance -= total_price

        user.save()
        car_rental.save()

        ctx = {"offer": offer, 'user': user, 'total_price': total_price}
        return render(request, "car_rent/car_rental_return_successful.html", context=ctx)


class CompleteDetails(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = CustomUserCompleteDetails()
        ctx = {"form": form}
        return render(request, "car_rent/account_complete_details.html", context=ctx)

    def post(self, request, *args, **kwargs):
        user = User.objects.get(id=request.user.id)
        form = CustomUserCompleteDetails(data=request.POST)
        ctx = {"form": form, "user": user}
        if form.is_valid():
            user.street = form.cleaned_data["street"]
            user.house_number = form.cleaned_data["house_number"]
            user.zip_code = form.cleaned_data["zip_code"]
            user.city = form.cleaned_data["city"]
            user.credit_card_nr = form.cleaned_data["credit_card_nr"]
            user.expiration = form.cleaned_data["expiration"]
            user.CVV = form.cleaned_data["CVV"]
            user.mobile = form.cleaned_data["mobile"]

            user.save(update_fields=["street", "house_number", "zip_code", "city",
                                     "credit_card_nr", 'expiration', 'CVV', 'mobile'])

            ctx['good_message'] = True
            messages.info(self.request, "You finished complete your details")
            return render(request, "car_rent/account_complete_details.html", context=ctx)
        messages.info(self.request, "Phone must be +00 123 345 678")
        return render(request, "car_rent/account_complete_details.html", context=ctx)


class AccountPayment(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = CustomUser.objects.get(id=request.user.id)
        form = PaymentForm()
        ctx = {'form': form, 'user': user}
        return render(request, "car_rent/account_payment.html", context=ctx)

    def post(self, request, *args, **kwargs):
        user = CustomUser.objects.get(id=request.user.id)
        form = PaymentForm(data=request.POST)
        if form.is_valid():
            if form.cleaned_data['credit_card_nr'] == user.credit_card_nr:
                if authenticate(username=user.email, password=form.cleaned_data['password']):
                    user.balance = user.balance + form.cleaned_data['balance']
                    user.save()

rent_and_deal_car/car_rent/templates/car_rent/account_complete_details.html
{% extends 'car_rent/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<h5>Settings</h5>
			<hr>
            <div>
				<a href="{% url 'car_rent:account-details' %}" class="btn btn-primary btn-lg active"
				   role="button" aria-pressed="true">
					Profile
				</a>
			</div>
			<br>
			<div>
				<a href="#" class="btn btn-primary btn-lg disabled" role="button" aria-pressed="true">
					Complete details
				</a>
			</div>
            <br>
			<div>
				<a href="{% url 'car_rent:account-payment' %}" class="btn btn-primary btn-lg active position-relative"
				   role="button" aria-pressed="true">
					Payment
				</a>
			</div>
		</div>
	</div>

	<div class="col-md-6">
		<div class="card card-body">
			<h2>Please make complete your details about account</h2>
                <form action="{% url 'car_rent:account-complete' %}" method="post"  class="">
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="label_text text-dark" for="street">Street</label>
                            <input type="text" class="form-control" name="street" id="street"
								   placeholder="Street" Required>
                        </div>
                        <div class="form-group col-md-6">
                            <label class="label_text text-dark" for="house_number">House number</label>
                            <input type="text" class="form-control" name="house_number" id="house_number"
								   placeholder="House Number" Required>
                        </div>
                        <div class="form-group col-md-3">
                            <label class="label_text text-dark" for="zip_code">Zip Code</label>
                            <input type="text" class="form-control" name="zip_code" id="zip_code"
								   placeholder="00-000" Required>
                        </div>
                        <div class="form-group col-md-3">
                            <label class="label_text text-dark" for="city">City</label>
                            <input type="text" class="form-control" name="city" id="city"
								   placeholder="City" Required>
                        </div>
                        <div class="form-group col-md-6">
                            <label class="label_text text-dark" for="mobile">Mobile</label>
                            <input type="text" class="form-control" name="mobile" id="mobile"
								   placeholder="+00 123 456 789" Required>
                        </div>

                    </div>
                    <hr>
                    <h2>Payment</h2>
                    <div class="form-group">
                        <label class="label_text text-dark" for="credit_card_nr">Credit card</label>
                        <input type="text" class="form-control" name="credit_card_nr" id="credit_card_nr"
							   placeholder="Credit card number" minlength="16"  maxlength="16" Required>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-3">
                            <label class="label_text text-dark " for="expiration">Expiration</label>
                            <input type="text" class="form-control" name="expiration" id="expiration"
                                   placeholder="11/24" maxlength="5" Required>
                        </div>
                        <div class="form-group col-md-3">
                            <label class="label_text text-dark" for="CVV">CVV</label>
                            <input type="text" class="form-control" name="CVV" id="CVV"
                                   placeholder="CVV" maxlength="3" Required>
                        </div>
                        </div>
                    <div class="d-grid gap-2 ">
                        <button type="submit" class="btn btn-success btn-lg custom_button">Confirm</button>
                        <a href="{% url 'car_rent:account-details'%}" class="btn btn-danger btn-lg" role="button" aria-pressed="true">Back</a>
                    </div>
                    <div class="form-group">
                        {% for message in messages %}
                            {% if good_message %}
                                <div class="alert alert-success" role="alert">
                                    {{message}}
                                </div>
                            {% else %}
                                <div class="alert alert-danger" role="alert">
                                    {{message}}
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </form>
		</div>
	</div>
</div>
{% endblock content %}

rent_and_deal_car/car_rent/templates/car_rent/account_details.html
{% extends 'car_rent/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<h5>Settings</h5>
			<hr>
			<div>
				<a href="#" class="btn btn-primary btn-lg disabled"
				   role="button" aria-pressed="true">
					Profile
				</a>
			</div>
			<br>
			<div>
				<a href="{% url 'car_rent:account-complete'%}" class="btn btn-primary btn-lg active position-relative"
				   role="button" aria-pressed="true">
					Complete details
					{% if count %}
						<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
							{{ count }}
						</span>
					{% endif %}
				</a>
			</div>
			<br>
			<div>
				<a href="{% url 'car_rent:account-payment' %}" class="btn btn-primary btn-lg active position-relative"
				   role="button" aria-pressed="true">
					Payment
				</a>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="card card-body">
			<h5>User Details </h5>
			<hr>
			<p>Name:  {{ user.first_name }} </p>
			<p>Surname:  {{ user.last_name }} </p>
			<p>Email:  {{ user.email }} </p>
			<p>Address:  {{ user.street }} {{ user.house_number }} {{ user.zip_code}} {{ user.city}}</p>
			<p>Card:  {{ user.credit_card_nr }} </p>
			<p>Mobile Number:  {{ user.mobile }} </p>

		</div>
		<div class="card card-body">
			{% if user.balance > 0 %}
				<h1>Balance: <span class="badge bg-success">{{ user.balance }} GR</span></h1>
			{% elif user.balance == 0 %}
				<h1>Balance: <span class="badge bg-primary">{{ user.balance }} GR</span></h1>
			{% else%}
				<h1>Balance: <span class="badge bg-danger">{{ user.balance }} GR</span></h1>
			{% endif%}
		</div>
	</div>
</div>
{% endblock content %}

rent_and_deal_car/car_rent/templates/car_rent/account_payment.html
{% extends 'car_rent/base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<h5>Settings</h5>
			<hr>
			<div>
				<a href="{% url 'car_rent:account-details' %}" class="btn btn-primary btn-lg active"
				   role="button" aria-pressed="true">
					Profile
				</a>
			</div>
			<br>
			<div>
				<a href="{% url 'car_rent:account-complete'%}" class="btn btn-primary btn-lg active"
				   role="button" aria-pressed="true">
					Complete details
				</a>
			</div>
			<br>
			<div>
				<a href="#" class="btn btn-primary btn-lg disabled"
				   role="button" aria-pressed="true">
					Payment
				</a>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="card card-body">
			<h5>Payment</h5>
			<hr>
			<form action="{% url 'car_rent:account-payment' %}" method="post">
				{% csrf_token %}
				<div class="form-group">
					<label for="credit_card_nr">Choose your card</label>
					<select class="form-select" name="credit_card_nr" id="credit_card_nr" aria-label="choose..">
						<option selected disabled >choose..</option>
						{% if user.credit_card_nr%}
							<option>{{ user.credit_card_nr }}</option>
						{% endif %}
					</select>
				</div>
				<br>

				<div class="form-group">
					<label for="balance">Amount to be paid </label>
					<input type="number" min="20" step="20" class="form-control" name="balance" id="balance" placeholder="Amount" required>
				</div>

				<br>

				<div class="form-group">
					<label for="password">Password</label>
					<input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
				</div>

				<div class="d-grid gap-2 ">
					<button type="submit" class="btn btn-success btn-lg custom_button">Confirm</button>
					<a href="{% url 'car_rent:account-details'%}" class="btn btn-danger btn-lg" role="button" aria-pressed="true">Back</a>
				</div>
				<div class="form-group">

					<br>
					{% if good_message %}
						{% for message in messages %}
							<div class="alert alert-success" role="alert">
								{{ message }}
							</div>
						{% endfor %}

					{% else %}

						{% for message in messages %}
							<div class="alert alert-danger" role="alert">
								{{message}}
							</div>
						{% endfor %}

					{% endif %}
                </div>
			</form>
		</div>
	</div>
</div>
{% endblock content %}

rent_and_deal_car/car_rent/templates/car_rent/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {%block title %}
    <title>base</title>
    {%endblock title %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossorigin="anonymous">
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'car_rent/css/style.css' %}">


</head>
<body>

<nav id="navbar-example2" class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'car_rent:home'%}">Golden Robert Car Dealer</a>

    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
        <a class="btn btn-primary" href="{% url 'car_rent:home'%}">Home</a>
        <a class="btn btn-primary" href="{% url 'car_rent:list-of-rental-offers'%}">Offer</a>
    </div>

    <ul class="nav nav-pills">
        {% if user.is_authenticated %}
        <div class="dropdown">

            <a href="#" class="nav-link link-success bi-person-circle user_circle" data-bs-toggle="dropdown"></a>

            <ul class="dropdown-menu dropdown-menu-lg-end">
                <li><a class="dropdown-item" href="{% url 'car_rent:account-details'%}">Account</a></li>
                {% if user.is_staff %}
                    <li><a class="dropdown-item" href="{% url 'car_rent:switch-admin'%}">Admin panel</a></li>
                {% endif %}
                <div class="dropdown-divider"></div>
                <li><a class="dropdown-item" href="{% url 'logout_user'%}">LOGOUT</a></li>
            </ul>
        </div>
        {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'register'%}">SIGN UP</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login_user'%}">LOGIN</a>
        </li>

        {% endif %}
    </ul>

</nav>

{% block content %}{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>

</html>

rent_and_deal_car/car_rent/templates/car_rent/car_rental.html
{% extends 'car_rent/base.html' %}

{% block content %}
    <form action = "{% url 'car_rent:car_rental' offer.id %}" method="POST">
        <div class="">
            <div class="container col-md-5 ">
                <div class="card card-body bg-info mb-3 border-primary mb-3">
                {% csrf_token %}

                {% if user %}
                    <h5>Client name: {{ user }}</h5>

                {% else  %}
                    <h5>Client mail: {{ user.email }}</h5>

                {% endif %}

                <p>Offer: {{ offer.Vehicle_Id.model_id }}</p>
                <p>Date of Rent: {{ date.day }}/{{ date.month }}/{{ date.year }}</p>
                <p>Deposit: {{ offer.Deposit}} GR</p>
                <p>Price per day: {{ offer.Price_per_day }} GR </p>
                <p>Total price: {{ price }} You will see after car return</p>

                <br>
                <br>

                {% if messages%}
                    <a href="{% url 'car_rent:list-of-rental-offers' %}" class="btn btn-danger"
                       role="button" aria-pressed="true">Back</a>
                {% else %}
                    <input type="submit" value="Confirm" class="btn btn-success">

                {% endif %}
                </div>
                <div class="form-group">
                    {% for message in messages %}
                        <div class="alert alert-danger" role="alert">
                            {{message}}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
{% endblock content %}

rent_and_deal_car/car_rent/templates/car_rent/car_rental_return.html
{% extends 'car_rent/base.html' %}

{% block content %}
    <form action = "{% url 'car_rent:car_rental_return' offer.id %}" method="POST">
        <div class="">
                <div class="container col-md-5 ">
                    <div class="card card-body bg-info mb-3 border-primary mb-3">
                        {% csrf_token %}
                        {% if user %}
                            <h5>Client name: {{user}}</h5>
                        {% else  %}
                            <h5>Client mail: {{user.email}}</h5>
                        {% endif %}
                        <p>Offer: {{offer.Vehicle_Id.model_id}}</p>
                        <p>Date of Rent: {{date }} </p>
                        <p>Price per day: {{ offer.Price_per_day }} GR </p>
                        <p>Total price: {{ total_price }} GR soon we take from your wallet</p>

                        <input type="submit" value="Return" class="btn btn-danger">
                   </div>
                </div>
         </div>
    </form>
{% endblock content %}

rent_and_deal_car/car_rent/templates/car_rent/list_of_offers.html
{% extends 'car_rent/base.html' %}

{% block content %}
<form action="{% url 'car_rent:list-of-rental-offers' %}" method="post">

    {% for offer in list_of_offers %}
        {% csrf_token %}
        {{ form }}
        <br>
        <div class="container ">
            <div class="col-md-6">
                <div class="card card-body bg-light mb-3 border-primary mb-3">

                    <h5>Model:{{offer.Vehicle_Id.model_id}} {{ offer.id }}</h5>
                    <p>Categories: {{offer.Categories}}</p>
                    <p>Description:{{offer.Description}}</p>
                    <p>Deposit: {{ offer.Deposit }}</p>
                    <p>Price_per_day: {{ offer.Price_per_day }}</p>



                    {% if rented == offer.id%}
                        <a class="btn btn-outline-danger btn-sm btn-block"
                           href="{% url 'car_rent:car_rental_return' offer.id %}">Return</a>
                    {% elif car_rental_availability %}
                        {% if offer.id in car_rental_availability %}
                            <a class="btn btn-secondary btn-sm btn-block disabled"
                                   href="#">Someone rented this car</a>
                        {% else%}
                            {% if rented %}
                                <a class="btn btn-outline-success btn-sm btn-block disabled" aria-disabled="true"
                                   href="#"> Rent </a>
                            {% else %}
                                <a class="btn btn-outline-success btn-sm btn-block " role="button" aria-disabled="true"
                                   href="{% url 'car_rent:car_rental' offer.id %}">Rent</a>
                            {% endif %}
                        {% endif %}
                    {% else %}
                        <a class="btn btn-outline-success btn-sm btn-block " role="button" aria-disabled="true"
                           href="{% url 'car_rent:car_rental' offer.id %}">Rent</a>
                    {% endif %}

                </div>
            </div>
        </div>
        <br>
    {% endfor %}
</form>
{% endblock content %}